# Generated by Django 3.2.8 on 2021-11-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='FinalOffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placementapp.offers'),
        ),
    ]
