# Generated by Django 3.2.8 on 2021-11-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='branch',
            field=models.ManyToManyField(to='placementapp.BranchDS'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='placementapp.branchds'),
        ),
    ]
