# Generated by Django 3.2.8 on 2021-11-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0002_auto_20211108_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='Name',
            field=models.CharField(default='SDE', max_length=100),
            preserve_default=False,
        ),
    ]
