# Generated by Django 3.2.8 on 2021-11-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0003_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Resume',
            field=models.FileField(blank=True, upload_to='Resume'),
        ),
        migrations.AlterField(
            model_name='applied',
            name='Status',
            field=models.CharField(choices=[('Selected', 'Selected'), ('EligibleForNextRound', 'EligibleForNextRound'), ('Rejected', 'Not Eligible For Next Round'), ('Under Evaluation', 'Under Evaluation')], default='UnderEvaluation', max_length=30),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='placementofficer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=10, null=True),
        ),
    ]
