# Generated by Django 3.2.8 on 2021-11-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0004_auto_20211117_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='maxCTC',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
