# Generated by Django 3.2.8 on 2021-11-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0005_student_maxctc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ResumeURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
